<x-layouts.app title="Two-Factor Authentication Setup">
  <div class="max-w-3xl mx-auto space-y-6">
    <div class="flex items-center gap-4 mb-8">
      <a href="{{ route('settings.index') }}" class="w-10 h-10 flex items-center justify-center rounded-xl bg-white dark:bg-slate-800 text-slate-500 hover:text-primary shadow-sm transition-colors border border-slate-200 dark:border-slate-700">
        <span class="material-icons">arrow_back</span>
      </a>
      <h1 class="text-2xl font-bold text-slate-900 dark:text-white">Enable Two-Factor Authentication</h1>
    </div>

    @if(session('error'))
      <div class="p-4 bg-rose-50 dark:bg-rose-900/20 border border-rose-200 dark:border-rose-800 rounded-xl flex items-center gap-3">
        <span class="material-icons text-rose-500">error</span>
        <p class="text-sm text-rose-700 dark:text-rose-400">{{ session('error') }}</p>
      </div>
    @endif

    <div class="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-700 p-6 md:p-8">
      <div class="prose dark:prose-invert max-w-none mb-8">
        <p>To use Two-Factor Authentication, you must install an authenticator application like <strong>Google Authenticator</strong>, <strong>Microsoft Authenticator</strong>, or <strong>Authy</strong> on your mobile device.</p>
        
        <h3>Step 1: Scan the QR Code</h3>
        <p>Open your authenticator app and scan the QR code below.</p>
      </div>

      <div class="flex flex-col md:flex-row items-center gap-8 mb-8">
        <div class="p-4 bg-white rounded-2xl border-2 border-slate-200 dark:border-slate-600 shadow-sm flex-shrink-0">
            <img src="{{ $qrCodeImg }}" alt="QR Code" class="w-48 h-48 rounded-lg">
        </div>
        
        <div class="flex-1 space-y-4 text-center md:text-left">
          <p class="text-sm text-slate-600 dark:text-slate-400">If you cannot scan the QR code, you can manually enter this setup key into your application:</p>
          <div class="inline-block px-4 py-2 bg-slate-100 dark:bg-slate-900 rounded-lg border border-slate-200 dark:border-slate-700">
            <code class="text-lg font-mono tracking-widest text-primary">{{ $secret }}</code>
          </div>
        </div>
      </div>

      <div class="border-t border-slate-200 dark:border-slate-700 pt-8">
        <h3 class="text-lg font-bold text-slate-900 dark:text-white mb-4">Step 2: Verify the Code</h3>
        <p class="text-sm text-slate-600 dark:text-slate-400 mb-6">Enter the 6-digit code generated by your authenticator app to confirm the setup.</p>
        
        <form method="POST" action="{{ route('settings.2fa.confirm') }}" class="max-w-sm">
          @csrf
          <div class="flex gap-4">
            <div class="flex-1">
              <input type="text" name="code" required autocomplete="off" placeholder="000000" maxlength="6" inputmode="numeric" pattern="[0-9]*"
                class="w-full px-4 py-3 bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-xl text-center text-lg font-mono tracking-[0.25em] focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none transition-all dark:text-white">
            </div>
            <button type="submit" class="bg-primary hover:bg-primary/90 text-white font-bold px-6 py-3 rounded-xl shadow-sm transition-all whitespace-nowrap">
              Verify
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</x-layouts.app>
